[package]
name = "rtm-mpi"
version.workspace = true
description.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
rtm-core.workspace = true
mpi.workspace = true

[[bin]]
name = "rtm_mpi"
path = "src/main.rs"
