[package]
name = "kanban"
version.workspace = true
description.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
kanban-core.workspace = true
clap.workspace = true
chrono.workspace = true
rand.workspace = true
wgpu.workspace = true
pollster.workspace = true
env_logger.workspace = true
log.workspace = true
tiny_http.workspace = true

[[bin]]
name = "kanban"
path = "src/main.rs"
