[package]
name = "rtm_mpi"
version = "1.1.2"
authors = ["th 2023"]
edition = "2021"
description = "rust-top_message, openMPI: Display message on top"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
chrono = "0.4.22"
rand = "0.8.5"
mpi = "0.6.0"

[profile.release]
lto = true

[profile.dev]
opt-level = 3
