[package]
name = "rust-top_message"
version = "1.0.0"
authors = ["th 2022"]
edition = "2021"
description = "Display message on top"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "*", features = ["derive"] }
chrono = "*"
rand = "*"

[profile.release]
lto = true

[profile.dev]
opt-level = 3
