[package]
name = "rtm_gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu.git", tag = "v0.18.0" }
pollster = "0.3.0"

[[bin]]
name = "{ name }"
path = "main.rs"
