[package]
name = "kanban-mpi"
version.workspace = true
description.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
kanban.workspace = true
mpi.workspace = true

[[bin]]
name = "kanban_mpi"
path = "src/main.rs"
