[package]
name = "rtm-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
rtm.workspace = true
yew.workspace = true
yew-router.workspace = true
web-sys.workspace = true
