name: cargo

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
      types:
       - closed

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: cargo version
        run: cargo --version
      - name: build
        run: cargo build --release

  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: rustup version
        run: rustup --version
      - name: rustup
        run: rustup component add rustfmt
      - name: cargo version
        run: cargo --version
      - name: rustfmt version
        run: cargo fmt --version
      - name: format
        run: cargo fmt
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[Action] cargo fmt'

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: rustup version
        run: rustup --version
      - name: rustup
        run: rustup component add clippy
      - name: cargo version
        run: cargo --version
      - name: clippy version
        run: cargo clippy --version
      - name: lint
        run: cargo clippy
