name: cargo

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: version
        run: cargo --version
      - name: build
        run: cargo build --release

  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: rustup
        run: rustup component add rustfmt
      - name: version
        run: cargo --version
      - name: format
        run: cargo fmt
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[Action] cargo fmt'

